### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by miknai** [dragonman225/notablog#11]
I am not able to run the generate command. Below is the error message I get.

```
Geonsoos-MacBook-Pro:notablog-starter geonsookim$ notablog generate .
I/notablog(20200929T234902.788): Copy theme assets
I/notablog(20200929T234902.815): Fetch Site Metadata
E/notablog-cli(20200929T234903.438): TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at parseTable (/usr/local/lib/node_modules/notablog/src/parse-table.js:26:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async generate (/usr/local/lib/node_modules/notablog/src/generate.js:86:20)
    at async cmdGenerate (/usr/local/lib/node_modules/notablog/bin/cli.js:34:5)
```

Not quite sure what causes this error. I attach the code for notablog-starter/config.json.
```
{
  "url": "https://www.notion.so/Ian_Kim-f4525e36d64047e6b51d714f6c93a8e6",
  "theme": "pure",
  "previewBrowser": "/usr/bin/chromium"
}
```

**Comment by dragonman225** [comment]
In the `url` field, you need to use a link to a **Table** like [this one](https://www.notion.so/b6fcf809ca5047b89f423948dce013a0?v=03ddc4d6130a47f8b68e74c9d0061de2), not a link to a **Page**.
