### ISSUE TITLE
errors happened when I generate blogs

### ISSUE THREAD

**Issue by gendlee** [dragonman225/notablog#50]
When I embed a block in my blog like this:
![企业微信截图_16842281722413](https://github.com/dragonman225/notablog/assets/14952400/cb876b38-229f-48c1-8119-3ed195e00de6)

**### errors happened when I generate blogs as follows**:
E/notablog-cli(20230516T165551.826): Error: Collection block df1ba7ae-c89d-4ab0-a826-458be76fa516 has no collection id
    at transformCollection (C:\Users\xxx\AppData\Roaming\npm\node_modules\notablog\node_modules\nast-util-from-notionapi\dist\index.js:440:15)
    at transformBlock (C:\Users\xxx\AppData\Roaming\npm\node_modules\notablog\node_modules\nast-util-from-notionapi\dist\index.js:908:24)
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\notablog\node_modules\nast-util-from-notionapi\dist\index.js:1120:16
    at Array.map (<anonymous>)
    at makeBlockArrayIntoTree (C:\Users\xxx\AppData\Roaming\npm\node_modules\notablog\node_modules\nast-util-from-notionapi\dist\index.js:1118:10)
    at Object.getOnePageAsTree (C:\Users\xxx\AppData\Roaming\npm\node_modules\notablog\node_modules\nast-util-from-notionapi\dist\index.js:1040:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async renderPost (C:\Users\xxx\AppData\Roaming\npm\node_modules\notablog\dist\index.js:818:16)

**Comment by dragonman225** [comment]
Maybe Notion changed their data format and it's now not fully recognized by Notablog. Unfortunately I don't have time to look into the problem at this moment.
