### ISSUE TITLE
error then notablog generate. seems config is wroing

### ISSUE THREAD

**Issue by skks11** [dragonman225/notablog#55]
W/notablog(20241116T135115.685): Error: ENOENT: no such file or directory, open 'themes/pure-ejs/layouts/.html'
    at Object.readFileSync (node:fs:441:20)
    at TemplateProvider._load (/Users/randomboog/.npm-global/lib/node_modules/notablog/dist/index.js:641:69)
    at TemplateProvider.get (/Users/randomboog/.npm-global/lib/node_modules/notablog/dist/index.js:629:36)
    at EJSStrategy.render (/Users/randomboog/.npm-global/lib/node_modules/notablog/dist/index.js:669:48)
    at Renderer.render (/Users/randomboog/.npm-global/lib/node_modules/notablog/dist/index.js:680:30)
    at renderPost (/Users/randomboog/.npm-global/lib/node_modules/notablog/dist/index.js:841:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'themes/pure-ejs/layouts/.html'
}
I/notablog(20241116T135115.884): Cache of "ec559948-e1d6-48ee-aee8-a68f003c81de" is saved
I/notablog(20241116T135115.884): Render published page "ec559948-e1d6-48ee-aee8-a68f003c81de"

**Comment by dragonman225** [comment]
From the error message `Error: ENOENT: no such file or directory, open 'themes/pure-ejs/layouts/.html'`, it seems like Notablog was trying to read a webpage layout called `.html`, which does not exist in the official theme (https://github.com/dragonman225/notablog-starter/tree/master/themes/pure-ejs/layouts).

Notablog has a hidden feature with which you can use a the `template` property in your Notion table to specify which webpage layout you want to use to wrap a generated page, but it is not used by the official theme at the moment, and you must set it to `post` for generation to work correctly.

Here's a checklist you can follow:

- Your Notion table has a column named `template` (case-sensitive) and its type is "Select".
- You have set an option for the property called `post` (case-sensitive).
- You have selected the `post` option for all Notion pages.

Like this screenshot:

<img width="836" alt="Image" src="https://github.com/user-attachments/assets/8270ba24-97b7-4291-bd9a-b73180a367da" />
